services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: perfume_bot_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always

    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI

    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data

  app:
    build: .
    container_name: perfume-bot-app
    restart: always
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      PG_DSN: postgres://postgres:postgres@postgres:5432/perfume_bot_db?sslmode=disable
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET: images
      PORT: 8080
      CHAT_ID: ${CHAT_ID}

volumes:
  postgres_data:
  minio_data: